### PR TITLE
Added remove silently for UpdateList

### PR DESCRIPTION
**Pull request by FancySensei**
If you are confident with your code you can now remove your update functions from the list without any throws.

### CODE REVIEW

**Comment by kkjamie** [comment]
Just to provide a bit of background on this.

The regular `Remove` function will throw if you try to remove a function that wasn't in the list, we want that because if you run into this situation it's symptomatic of some incorrect logic in your code, and we want you to know so you can go fix this. Without this we maybe hiding bugs.

On the other hand checking this is slower, given the performance critical context (it's an update list, it does a *list* of things *every frame*), it's nice to have a function that is highly optimized.

My concerns for this are how do we indicate which function you should use. Many people may get the exceptions and instead of hunting down the problem, they see `RemoveSilently` and go with that one.

I'm also conflicted on the whole update list being public, as documented #22. It's from the `duck-tween` 
 library rather than `duck-utils` part of me thinks it's only use case should be within this library, and we can make it `internal`. It never feels right "Borrowing" a util from a library you have used for another purpose. I wouldn't be opposed to adding a type of update list into `duck-utils` for public use

**Comment by kkjamie** [comment]
it maybe more beneficial to keep the API as a single function, and use scripting defines. So in regular dev environment you get the check and the throw, but in production, you get maximum performance and no chance to throw and crash the application. 

That way there is no ambiguity between API and no temptation to use the "silent" one to lazily get rid of your errors.

**Comment by FancySensei** [comment]
Yeah I agree the UpdateList deserves a separated space rather than hiding in the mighty tween umbrella.

I don't think the compiler flag would work, however. It's too hard to pre-define some flags for all those random projects outside the world.

I think it's the users' responsibility to do things like:
```
#if PRODUCTION
    updateList.RemoveSilently(blah);
#else
    updateList.Remove(blah);
#endif
```

**Comment by FenrirWillow** [comment]
Instead of `RemoveSilently`, perhaps this function can be named `RemoveUnsafe`. Several APIs in Unreal for example use this notation. There is also a hidden contract that Unsafe usually means you are skipping some step (locking, bounds checks etc.). Don't know how you feel about it @kkjamie in terms of general Duck context.

**Comment by kkjamie** [comment]
@FenrirWillow I agree. 

However in this case as discussed previously I think we should make this particular utility internal to this library, making chuan's changes redundant. I think we can create a similar thing for public use with this kind of API seperately, and it can go into `duck-util`.

**Pull request closed without merging**
